services:
  db:
    image: mysql:latest
    container_name: PJ01-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PJ01
    volumes:
      - PJ01:/var/lib/mysql     
    ports:
      - "3307:3306"  
    networks:
      - PJ01
  phpmyadmin: 
    image: phpmyadmin:latest
    container_name: PJ01-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
       - '8080:80' 
    depends_on:
       - db   
    networks:
       - PJ01
networks:
  PJ01:
    driver: bridge
volumes:
  PJ01:
    driver: local