services:
  db:
    image: mysql:latest
    container_name: std03-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: STD03
    volumes:
      - STD03:/var/lib/mysql     
    ports:
      - "3307:3306"  
    networks:
      - STD03
  phpmyadmin: 
    image: phpmyadmin:latest
    container_name: std03-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
       - '8080:80' 
    depends_on:
       - db   
    networks:
       - STD03 
networks:
  STD03:
    driver: bridge
volumes:
  STD03:
    driver: local